baseURL = 'https://vercastro.github.io/vercan-web/'
languageCode = 'en-us'
title = 'vercan'
theme = "gallery"

[params]
  description = 'A showcase of my photography'
  author = 'vercan'
  defaultTheme = 'dark' # 'dark', 'light', or 'system'
