baseURL = 'https://vercastro.github.io/vercan-web/'
locale = 'en-us'
title = 'vercan'
theme = "gallery"

[params]
  description = 'A showcase of my photography'
  defaultTheme = 'dark' # 'dark', 'light', or 'system'

  [params.author]
    name = 'vercan'
