baseURL = 'https://vercastro.github.io/vercan-web/'
locale = 'en-us'
title = 'vercan.ca'
theme = "gallery"

[params]
  description = 'A showcase of my photography'
  defaultTheme = 'dark' # 'dark', 'light', or 'system'

  [params.author]
    name = 'vercan'

# Custom Top Navigation Bar
[[menu.main]]
  name = "Albums"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

# Append to your hugo.toml to omit raw photo downloads
#cascade:
#  build:
#    publishResources: false
